name: Test Reusable WorkFlow user

on: 
  workflow_dispatch:
  pull_request:
    branches: [ develop ]

jobs:
  do-it: 
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run docker action
        uses: cesarsturion/reusable-workflow/.github/workflows/createpublishdockerimage.yml@main
        with:
          image_name: node-helloworld-github-actions
          tag: $GITHUB_RUN_NUMBER
        secrets:
          registry_username: ${{ secrets.DOCKER_USER }}
          registry_password: ${{ secrets.DOCKER_PASSWORD }}






