name: Notify on Release
on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/*'
      - '!master'
      - '!main'
  pull_request:
    branches: 
      - 'master'
      - 'main'
  release:
    types:
      - 'created'

jobs:
  slack-message:
    runs-on: ubuntu-latest
    steps: 
      - name: Set Text
        run: echo "MESSAGE=Send text in Slack" >> $GITHUB_ENV


      - name: Text Message
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/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

      - name: Slack Message
        run: |
          curl -X POST -H 'content-type: application/json' -- data '{"text":"Send text in Slack"}' ${{ secrets.SLACK_WEBHOOK }}