name: Notify on Release
on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/*'
      - '!master'
      - '!main'
  pull_request:
    branches: 
      - 'master'
      - 'main'
  release:
    types:
      - 'created'

jobs:
  slack-message:
    runs-on: ubuntu-latest
    steps: 

      - name: Text Message
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World! >>> ${{ github.run_id }} <<<"}' https://hooks.slack.com/services/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