name: Notify on Release
on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/*'
      - '!master'
      - '!main'
  pull_request:
    branches: 
      - 'master'
      - 'main'
  release:
    types:
      - 'created'

jobs:
  slack-message:
    runs-on: ubuntu-latest
    steps: 
      - name: Set Text
        run: echo "MESSAGE=Send text in Slack" >> $GITHUB_ENV


      - name: Text Message
        run: |
           curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/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

      # - name: Slack Notification
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_CHANNEL: general
      #     SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
      #     SLACK_ICON: https://github.com/rtCamp.png?size=48
      #     SLACK_MESSAGE: 'Post Content :rocket:'
      #     SLACK_TITLE: Post Title
      #     SLACK_USERNAME: csturion
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          #SLACK_USERNAME: ThisIsMyUsername # Optional. (defaults to webhook app)
          SLACK_CHANNEL: general # Optional. (defaults to webhook)
          SLACK_AVATAR: repository # Optional. can be (repository, sender, an URL) (defaults to webhook app avatar)
        uses: Ilshidur/action-slack@2.0.2
        with:
          args: 'A new commit has been pushed.' # Optional


      # - name: Slack Message
      #   run: |
      #     curl -X POST -H 'content-type: application/json' -- data '{"text":"Send text in Slack, ###${{github.run_number}}###"}' ${{ secrets.SLACK_WEBHOOK }}